spring.application.name=FootGoat
spring.datasource.url=jdbc:postgresql://localhost:5432/footgoat
spring.datasource.username=postgres
spring.datasource.password=${POSTGRES_PASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
